### ISSUE TITLE
"Couldn't launch Dash" with every query

### ISSUE THREAD

**Issue by fabdrol** [willfarrell/alfred-dash-workflow#13]
It simply doesn't seem to work. Versions:
OS X: 10.8.5
Alfred: 2.1 (218)
Dash: v1.11

![screen shot 2013-10-25 at 17 44 26](https://f.cloud.github.com/assets/123201/1409063/5b0c5a26-3d8c-11e3-9212-e97f6619527c.png)

**Comment by miroamarillo** [comment]
Same Issue here

OS X: 10.10.4
Alfred: 2.7.1
Dash: 3.1.0

Fresh install of OS X.  Any ideas?

**Comment by willfarrell** [comment]
This workflow is no longer necessary. There is a new workflow built into Dash under the plugins settings. You should install that workflow.

**Comment by miroamarillo** [comment]
Got it working per your suggestion.  Thanks a lot!!

**Comment by xyxzfj** [comment]
willfarrell's answer is correct. There is a new workflow built into Dash under the plugins settings.
